name: Lint and Compile
on: pull_request
jobs:
  lint-and-compile:
    name: Lint and Compile
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: |
          # Add cc65 APT Repository
          echo 'deb https://download.opensuse.org/repositories/home:/strik/xUbuntu_23.04/ /' | \
          sudo tee /etc/apt/sources.list.d/home:strik.list
          curl -fsSL https://download.opensuse.org/repositories/home:strik/xUbuntu_23.04/Release.key | \
          gpg --dearmor | \
          sudo tee /etc/apt/trusted.gpg.d/home_strik.gpg > /dev/null

          # Add LLVM/Clang APT Repository
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 20

          # Update and Install
          sudo apt-get update
          sudo apt-get install -y ninja-build cc65 clang-tidy-20
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run ClangFormat
        uses: DoozyX/clang-format-lint-action@v0.18.2
        with:
          source: src
      - name: CMake Configure and Build
        run: |
          cmake -DCMAKE_C_COMPILER=clang-20 --preset native-release
          cmake --build build-native-release
      - name: Make Build
        run: |
          make CC65_LIB_PATH=/usr/share/cc65/lib NO_CLANG_FORMAT=true BUILD_TYPE=Release
      - name: Run ClangTidy
        run: |
          make lint NO_CLANG_FORMAT=true
      - name: Set Environment Variables
        run: |
          echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
      - name: Rename Executable
        run: |
          sudo mv build-c128-release/yap-lang.prg build-c128-release/yap-lang-${{ github.head_ref }}-${{ env.sha_short }}.prg
          sudo mv build-native-release/yap-lang-native build-native-release/yap-lang-native-${{ github.head_ref }}-${{ env.sha_short }}
      - name: Upload Executable
        uses: actions/upload-artifact@v4
        with:
          name: yap-lang-${{ github.head_ref }}-${{ env.sha_short }}
          path: |
            build-c128-release/yap-lang-${{ github.head_ref }}-${{ env.sha_short }}.prg
            build-native-release/yap-lang-native-${{ github.head_ref }}-${{ env.sha_short }}
